#!/usr/bin/python3
def raise_exception():
    _ = 1 / ""
